### ISSUE TITLE
Python exceptions caused by plotting scripts

### ISSUE THREAD

**Issue by dietmarw** [xogeny/ModelicaBook#189]
When compiling i get python exceptions from:
 * SV1.py
 * SV1U.py
 * SV2.py
 * SV2T.py

All of the same nature:
```
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/matplotlib/sphinxext/plot_directive.py", line 515, in run_code
    exec code in ns
  File "<string>", line 4, in <module>
  File "/home/dietmarw/.workspace/ModelicaBook/text/source/_sphinxext/xogeny/plot_utils.py", line 109, in render_simple_plot
    raise NameError("Unknown key: "+var0name+" among "+str(res.names()))
```

**Comment by dietmarw** [comment]
No longer an issue it seems.
